# Generated by Django 5.0.3 on 2024-03-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
    ]
