# Generated by Django 5.0.3 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='players', to='api.card'),
        ),
    ]
