# Generated by Django 5.0.3 on 2024-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_player_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points_to_win',
            field=models.IntegerField(default=10),
        ),
    ]
