# Generated by Django 5.0.3 on 2024-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_game_last_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='join_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
