# Generated by Django 5.0.3 on 2024-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_game_join_code_alter_game_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.card'),
        ),
    ]
